version: "3.8"
networks:
  life-style-go:
    driver: bridge
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app/
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - life-style-go
  redis:
    hostname: redis
    # image: redis:latest
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - life-style-go
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - life-style-go
